import express from 'express';
import { getAllTrends, createCart, updateCart, deleteCart, getCartById } from '../Controllers/fashionController.js';

const router = express.Router();// why is this router object created here? The router object is created here to define and handle routes for the fashion-related endpoints. It allows us to group related routes together and apply middleware or route-specific logic to them. By using the router, we can keep our code organized and modular, making it easier to manage and maintain.

router.get("/", getAllTrends);// why is this route defined here? This route is defined here to handle GET requests to the root endpoint ("/") of the fashion routes. When a GET request is made to this endpoint, the getAllTrends function from the fashionController.js file will be executed. This function retrieves all fashion trends from the database and sends them back to the client in JSON format.
router.get("/:id", getCartById);
router.post("/", createCart);// why is this route defined here? This route is defined here to handle POST requests to the root endpoint ("/") of the fashion routes. When a POST request is made to this endpoint, the createCart function from the fashionController.js file will be executed. This function creates a new cart in the database based on the data sent in the request body and sends back the created cart in JSON format.
router.put("/:id",updateCart);// why is this route defined here? This route is defined here to handle PUT requests to the endpoint ("/:id") of the fashion routes. The ":id" part of the endpoint is a route parameter that represents the unique identifier of the cart to be updated. When a PUT request is made to this endpoint, the updateCart function from the fashionController.js file will be executed. This function updates the cart with the specified ID in the database based on the data sent in the request body and sends back a success message in JSON format.
router.delete("/:id", deleteCart);// why is this route defined here? This route is defined here to handle DELETE requests to the endpoint ("/:id") of the fashion routes. The ":id" part of the endpoint is a route parameter that represents the unique identifier of the cart to be deleted. When a DELETE request is made to this endpoint, the deleteCart function from the fashionController.js file will be executed. This function deletes the cart with the specified ID from the database and sends back a success message in JSON format.

export default router;// why is this export statement used here? This export statement is used here to make the router object available for import in other files. By exporting the router, we can import it in the server.js file and use it as middleware to handle requests to the fashion routes. This allows us to organize our code and separate the route definitions from the main server file.